Global:
  BaseProbability: 0.1
  LogLevel: DEBUG    # Possible Values:  ALL, DEBUG, INFO, WARNING, ERROR, NONE
Whitelist:
  flowerable: []
  walkable:   [7,8]
  flyable:    [1,2,3,4,5,6,7,8,9,10,11,28,29,30,31,32,33,34,35,36,37]
Hard:
  FieldProperties:
    flowerable: 1
    walkable:   8
    flyable:    9
Medium:
  FieldProperties:
    flowerable: 7
    walkable:   9
    flyable:    6
Easy:
  FieldProperties:
    flowerable: 3
    walkable:   8
    flyable:    9
